#module: default
version: 3
runtime: custom
vm: true
api_version: 1
threadsafe: yes
manual_scaling:
  instances: 1
instance_class: B4_1G
health_check:
  enable_health_check: False
handlers:
# Serve images as static resources.
- url: /(.*)$
  script: \1
skip_files:
- ^(.*/)?\.zip$
- ^(.*/)?\.bat$
- ^(.*/)?\.sh$
- ^(.*/)?\.md$
