#module: default
version: 2
runtime: custom
vm: true
api_version: 1
threadsafe: yes
manual_scaling:
  instances: 1
instance_class: B4_1G
health_check:
  enable_health_check: False
# Serve php scripts.
handlers:
  - url: /(.*)$
    script: \1
#To enable access to the Zend Server console then uncomment the lines below
#network:
#  forwarded_ports:
#    - 10081
#    - 10082
